version: '3.8'

services:
  mars-weather-app:
    container_name: mars-weather-app
    image: docker.prorickey.xyz/prorickey/smathhacks25:0.1.0
    restart: always
    ports:
      - "3456:3000"
    depends_on:
      - mars-weather-db
    environment:
      - KEY=CYcagejUv3tJwTfEQMWxrF2ALnkVm87RP5hNybHZBDXdGu9zsK
      - DATABASE_URL=postgresql://mars:pass@mars-weather-db:5432/weather

  mars-weather-db:
    image: postgres
    container_name: mars-weather-db
    restart: always
    ports:
      - "7239:5432"
    environment:
      POSTGRES_USER: mars
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: weather
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
